// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH40aMuXF78uj5h11es9qZqQyFgDP9Fs4',
    appId: '1:312283628851:web:72b572aed133e3cdd62a46',
    messagingSenderId: '312283628851',
    projectId: 'ornate-axiom-416310',
    authDomain: 'ornate-axiom-416310.firebaseapp.com',
    storageBucket: 'ornate-axiom-416310.firebasestorage.app',
    measurementId: 'G-C8H8RHQYM4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoJtSD_qLOIm4phicpryVPqeLj-MwnKGM',
    appId: '1:312283628851:ios:1b01f1fcb46e7badd62a46',
    messagingSenderId: '312283628851',
    projectId: 'ornate-axiom-416310',
    storageBucket: 'ornate-axiom-416310.firebasestorage.app',
    iosClientId: '312283628851-87fokdk4ds7ku6ver83juiq03o962get.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionvehicule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoJtSD_qLOIm4phicpryVPqeLj-MwnKGM',
    appId: '1:312283628851:ios:1b01f1fcb46e7badd62a46',
    messagingSenderId: '312283628851',
    projectId: 'ornate-axiom-416310',
    storageBucket: 'ornate-axiom-416310.firebasestorage.app',
    iosClientId: '312283628851-87fokdk4ds7ku6ver83juiq03o962get.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionvehicule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH40aMuXF78uj5h11es9qZqQyFgDP9Fs4',
    appId: '1:312283628851:web:fde2cdb774a4d135d62a46',
    messagingSenderId: '312283628851',
    projectId: 'ornate-axiom-416310',
    authDomain: 'ornate-axiom-416310.firebaseapp.com',
    storageBucket: 'ornate-axiom-416310.firebasestorage.app',
    measurementId: 'G-G6HTDQEF4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFWljJ8ySTPhn_uLHJOJjCjB4U4ROkeg',
    appId: '1:312283628851:android:a8173eaf1bd39638d62a46',
    messagingSenderId: '312283628851',
    projectId: 'ornate-axiom-416310',
    storageBucket: 'ornate-axiom-416310.firebasestorage.app',
  );

}